new questionData("What is the regex expression used to match anything that's NOT a letter (not a, b, c, A, B, etc)",1,"[^a-zA-Z]/n","[^a-zA-Z]","[^a-zA-Z]/x"),
new questionData("Which of these regex expressions is NOT used for finding 3 digits in a row?",2,"/\d{3}/","/[0-9][0-9][0-9]/","/\{3}d/"),
new questionData("What is the github command for listing all local and remote branches?",1,"git branch -a","git branch","git branch -d"),
new questionData("What is the github command for listing any files that have been changed?",1,"git branch","git status","git merge"),
new questionData("What does the '-m' flag do in the github command 'git commit -m...'?" ,2,"Denotes the commit is for the master branch","Prepares the commit ready for a merge","Allows the user to create a message for the commit"),
new questionData("In Github, what is the shorthand name for the remote repository, where the project was originally cloned from?",0,"origin","master","checkout"),
